---
include:
  - board: nice_nano
    shield: dac_man_5x6_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: dac_man_5x6_right
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: settings_reset
